name = "KAT House Positions";
dir = "@KHP";
author = "Katalam";
picture = "book.paa";
logo = "book.paa";
logoOver = "book.paa";
overviewPicture = "book.paa";
actionName = "Github";
action = "https://github.com/Katalam/KHP";
