// Generated by extract_furniture.py - do not edit by hand.
class CfgHouseData
{
    class Land_MultistoryBuilding_03_F
    {
        class Room1
        {
            class Variant1
            {
                types[] = {"Land_CratesShabby_F", "Land_ToiletBox_F"};
                x[] = {-4.6428, -5.8227};
                y[] = {-25.1454, -24.6853};
                z[] = {4.5206, 5.0103};
                yaw[] = {0.000, 180.000};
            };
            class Variant2
            {
                types[] = {"Land_GarbageContainer_closed_F", "Land_GarbageContainer_closed_F"};
                x[] = {-3.6291, -5.6176};
                y[] = {-25.1213, -25.1213};
                z[] = {4.3521, 4.3345};
                yaw[] = {0.000, 0.000};
            };
        };
    };
    class Land_House_Big_04_F
    {
        class Room1
        {
            class Variant1
            {
                types[] = {"Land_WoodenBed_01_F", "Land_ChairWood_F", "Land_TableBig_01_F", "Land_Rug_01_F", "Land_Sofa_01_F"};
                x[] = {2.2986, -1.6736, -1.7632, 2.3376, -6.0100};
                y[] = {-2.4927, -2.9492, -2.5041, -2.9379, -2.4505};
                z[] = {-4.3570, -2.5669, -1.7486, -2.3658, -4.1519};
                yaw[] = {178.857, 130.824, 0.000, 270.997, 92.541};
            };
            class Variant2
            {
                types[] = {"Land_WoodenBed_01_F", "Land_ChairWood_F", "Land_TableBig_01_F", "Land_ChairWood_F", "Land_ShelvesWooden_F"};
                x[] = {2.0781, -3.1621, -2.0947, -1.9754, -6.2276};
                y[] = {-2.4927, -2.9492, -2.5041, -2.9492, -2.4468};
                z[] = {-2.3228, -4.4595, -4.3028, -2.7554, -4.8658};
                yaw[] = {359.866, 233.099, 90.947, 27.355, 181.583};
            };
        };
        class Room2
        {
            class Variant1
            {
                types[] = {"Land_WoodenBed_01_F", "Land_Rug_01_F", "Land_ChairWood_F", "Land_ChairWood_F", "Land_TableBig_01_F", "Land_ShelvesWooden_F"};
                x[] = {-5.6194, -3.7395, 3.6545, 3.9800, 3.5769, -2.2554};
                y[] = {0.7573, 0.3121, 0.3008, 0.3008, 0.7459, 0.8032};
                z[] = {1.9316, 1.9419, 1.8144, 4.3457, 2.9306, 4.7568};
                yaw[] = {178.857, 359.477, 130.824, 61.748, 359.425, 88.525};
            };
            class Variant2
            {
                types[] = {"Land_Rug_01_F", "Land_ChairWood_F", "Land_TableBig_01_F", "Land_WoodenBed_01_F"};
                x[] = {1.6455, -4.6494, -3.8325, 3.6643};
                y[] = {0.3121, 0.3008, 0.7459, 0.7573};
                z[] = {2.7880, 2.2876, 1.3520, 2.8037};
                yaw[] = {359.477, 304.770, 359.425, 89.962};
            };
        };
    };
    class Land_House_Big_03_F
    {
        class Room1
        {
            class Variant1
            {
            };
        };
    };
    class Land_School_01_F
    {
        class Room1
        {
            class Variant1
            {
            };
        };
    };
    class Land_MultistoryBuilding_04_F
    {
        class Room1
        {
            class Variant1
            {
            };
        };
    };
    class Land_MultistoryBuilding_01_F
    {
        class Room1
        {
            class Variant1
            {
            };
        };
    };
    class Land_Shop_City_07_F
    {
        class Room1
        {
            class Variant1
            {
            };
        };
    };
    class Land_Shop_City_06_F
    {
        class Room1
        {
            class Variant1
            {
            };
        };
    };
    class Land_Shop_City_03_F
    {
        class Room1
        {
            class Variant1
            {
            };
        };
    };
    class Land_Shop_City_05_F
    {
        class Room1
        {
            class Variant1
            {
            };
        };
    };
    class Land_Addon_04_F
    {
        class Room1
        {
            class Variant1
            {
            };
        };
    };
    class Land_Addon_01_F
    {
        class Room1
        {
            class Variant1
            {
            };
        };
    };
    class Land_Addon_05_F
    {
        class Room1
        {
            class Variant1
            {
            };
        };
    };
    class Land_Addon_03_F
    {
        class Room1
        {
            class Variant1
            {
            };
        };
    };
    class Land_Addon_02_F
    {
        class Room1
        {
            class Variant1
            {
            };
        };
    };
    class Land_House_Big_05_F
    {
        class Room1
        {
            class Variant1
            {
            };
        };
    };
    class Land_Shop_City_04_F
    {
        class Room1
        {
            class Variant1
            {
            };
        };
    };
    class Land_Shop_City_02_F
    {
        class Room1
        {
            class Variant1
            {
            };
        };
    };
    class Land_Shop_City_01_F
    {
        class Room1
        {
            class Variant1
            {
                types[] = {"Land_CashDesk_F", "Land_Icebox_F", "Land_Icebox_F", "Land_Metal_rack_Tall_F", "Land_Metal_rack_Tall_F", "Land_Metal_rack_Tall_F"};
                x[] = {3.0610, 3.0212, 6.3923, 2.8589, 3.7309, 4.6184};
                y[] = {-4.9652, -4.3260, -4.3260, -4.9483, -4.9483, -4.9483};
                z[] = {0.8428, -1.0317, 5.1504, 5.3521, 5.3360, 5.3355};
                yaw[] = {271.025, 270.864, 359.567, 0.000, 0.000, 0.000};
            };
            class Variant2
            {
                types[] = {"Land_CashDesk_F", "Land_Rack_F", "Land_Rack_F", "Land_Rack_F", "Land_Rack_F", "Land_ShelvesMetal_F", "Land_ShelvesMetal_F", "Land_ShelvesMetal_F"};
                x[] = {6.3347, 0.0322, 0.0368, 0.0293, 0.9258, 2.5229, 2.5112, 3.5459};
                y[] = {-4.9483, -4.1324, -4.1324, -4.1324, -4.1340, -4.9454, -4.9599, -4.9502};
                z[] = {2.6953, -1.2744, 0.1768, 1.6289, 4.3770, -0.8818, 1.2378, 3.7818};
                yaw[] = {0.000, 0.000, 0.000, 0.000, 46.252, 0.000, 0.000, 90.099};
            };
        };
    };
    class Land_House_Small_05_F
    {
        class Room1
        {
            class Variant1
            {
                types[] = {"Land_ChairWood_F", "Land_Rug_01_Traditional_F", "Land_Sofa_01_F", "Land_WoodenTable_small_F", "C_Offroad_02_unarmed_F"};
                x[] = {-0.1316, -0.8300, -3.4338, 1.0723, -1.6145};
                y[] = {-1.0882, -1.0762, -0.5890, -0.6553, 0.4833};
                z[] = {4.7979, 1.5044, 3.7354, 4.4912, -3.3877};
                yaw[] = {310.089, 0.000, 89.786, 0.000, 269.274};
            };
            class Variant2
            {
                types[] = {"Land_OfficeCabinet_02_F", "Land_OfficeChair_01_F", "OfficeTable_01_old_F", "Land_RattanChair_01_F", "Land_RattanChair_01_F", "Land_RattanTable_01_F", "Land_Rug_01_Traditional_F"};
                x[] = {-3.5354, -1.4243, -1.6103, -2.4467, -0.3257, -1.4101, -1.1054};
                y[] = {-0.3058, -0.4121, -0.6639, -0.5293, -0.5293, -0.6892, -1.0763};
                z[] = {-1.1787, -0.1494, -1.0493, 4.6953, 4.6431, 4.6817, 2.1953};
                yaw[] = {181.255, 0.000, 180.393, 276.714, 90.411, 0.000, 91.336};
            };
        };
    };
    class Land_House_Small_04_F
    {
        class Room1
        {
            class Variant1
            {
                types[] = {"OfficeTable_01_old_F", "Land_OfficeChair_01_F", "Land_OfficeCabinet_02_F", "Land_Sofa_01_F", "Land_Bench_F", "Land_Sun_chair_F", "Land_ChairPlastic_F", "Land_ChairPlastic_F"};
                x[] = {3.9910, 3.0164, 1.4349, -1.6528, 0.5916, -3.5573, -1.7802, -0.1457};
                y[] = {-0.4438, -0.1918, -0.0857, -0.3681, -0.6195, -0.4570, -0.3841, -0.3841};
                z[] = {-1.4765, -0.9565, -0.2622, -3.7465, 3.3619, 2.9917, -5.7856, -5.7426};
                yaw[] = {91.115, 301.091, 359.534, 88.204, 0.000, 326.009, 49.474, 113.204};
            };
            class Variant2
            {
                types[] = {"Land_ArmChair_01_F", "Land_WoodenBed_01_F", "Land_ChairPlastic_F", "Land_FlowerPot_01_Flower_F", "Land_ShelvesWooden_F", "Land_ShelvesWooden_F", "C_Offroad_02_unarmed_F"};
                x[] = {3.4268, -1.1853, -3.7304, 0.6531, 0.6236, 0.6326, 0.2808};
                y[] = {-0.3824, -0.4103, -0.3841, -0.0651, -0.3644, -0.3644, 0.7034};
                z[] = {-1.2602, -4.0122, -2.8276, 1.0830, 3.2535, 2.0806, -7.0649};
                yaw[] = {232.013, 270.838, 248.403, 93.201, 0.000, 0.000, 269.284};
            };
        };
    };
};
