name = "Katalam House Positions"
author = "Katalam"
prefix = "KHP"
mainprefix = "z"


[hemtt.launch.default]
workshop = [
    "450814997", # CBA_A3's Workshop ID
    "463939057", # ACE3's Workshop ID
]

parameters = [
    "-skipIntro",
    "-noSplash",
    "-showScriptErrors",
    "-debug",
    "-filePatching",
]
